Proyecto_flask/app/payment/views.py
from flask import Blueprint, Response, request, render_template, redirect, url_for, flash
from app.payment.forms import AddPaymentForm
from app.db import db
from app.payment.models import Payments
from flask_login import current_user, login_required

payment = Blueprint("payment", __name__, url_prefix="/payment")

@payment.route('/add-payment-method', methods=['GET', 'POST'])
@login_required
def add_payment_form():

    """
        Add payment method
        ---
        tags:
            - Payment
        description: Register a new form of payment in the DB for the logged in user
        responses:
            200:
                description: Ok
            405:
                description: Method not allowed
    """

    form_payment = AddPaymentForm()
    if request.method == 'POST' and form_payment.validate():
        new_payment = Payments(id=form_payment.id.data, bank=form_payment.bank.data, user_id=current_user.id)
        db.session.add(new_payment)
        db.session.commit()
        return redirect(url_for('products.show_products_catalog'))
    return render_template('add_payment_form.html', form=form_payment)

Proyecto_flask/app/shopping/views.py
from flask import Blueprint, Response, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user

car = Blueprint("car", __name__, url_prefix="/car")

@car.route('/shopping-car', methods=['GET'])
@login_required
def show_shopping_car():

    """
        Add product at shopping car
        ---
        tags:
            - Shopping
        description: Allows to see the products added in the shopping car and calculate the total and subtotal
        responses:
            200:
                description: Ok
            405:
                description: Method not allowed
    """

    my_info = {"name": current_user.name, "email": current_user.email}
    return render_template('shopping.html', my_info=my_info)

Proyecto_flask/app/templates/add_payment_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <title>Add Payment Method</title>
</head>

<body>
    <div class="hero-head">
        <nav class="navbar" style="background-color: mediumslateblue;">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="{{ url_for('products.show_products_catalog') }}" class="navbar-item">
                            Catalog
                        </a>
                        <a href="{{ url_for('payment.add_payment_form') }}" class="navbar-item">
                            Add payment method
                        </a>
                        <a href="{{ url_for('auth.show_my_profile') }}" class="navbar-item">
                            My profile
                        </a>
                        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                            Logout
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 my-4 mx-auto text-center">
        <h1 class="display-4 mt-4">Add Payment Method</h1>
    </div>
    <form method="POST" action="/payment/add-payment-method" style="text-align: center;">
        {{ form.csrf_token }}
        {{ form.id.label }} {{ form.id(size=20) }}<br />
        {{ form.bank.label }} {{ form.bank(size=60) }}<br />
        <input type="submit" value="Confirm">
    </form>
</body>

</html>

Proyecto_flask/app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pygroup Shop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-fullheight" style="background: royalblue">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

Proyecto_flask/app/templates/catalog.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <title>Products Catalog</title>
</head>

<body>
    <div class="" style="background-color: mediumslateblue;">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: mediumslateblue;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <img src="https://image.flaticon.com/icons/png/512/116/116356.png"
                            class="nav-link dropdown-toggle img-fluid" height="70px" width="70px" href="#"
                            id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></img>
                        <div id="carrito" class="dropdown-menu" aria-labelledby="navbarCollapse">
                            <table id="lista-carrito" class="table">
                                <thead>
                                    <tr>
                                        <th>Imagen</th>
                                        <th>Nombre</th>
                                        <th>Precio</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>

                            <a href="#" id="vaciar-carrito" class="btn btn-primary btn-block">Vaciar Carrito</a>
                            <a href="#" id="procesar-pedido" class="btn btn-danger btn-block">Procesar
                                Compra</a>
                        </div>
                    </li>
                </ul>
            </div>
            <a href="{{ url_for('products.show_products_catalog') }}" class="navbar-item">
                Catalog
            </a>
            <a href="{{ url_for('payment.add_payment_form') }}" class="navbar-item">
                Add payment method
            </a>
            <a href="{{ url_for('auth.show_my_profile') }}" class="navbar-item">
                My profile
            </a>
            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                Logout
            </a>
        </nav>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 my-4 mx-auto text-center">
        <h1 class="display-4 mt-4">Lista de Productos</h1>
        <p class="lead">Selecciona uno de nuestros productos y con su id añadelo al carrito</p>
    </div>

    <div class="container" id="lista-productos">
        <div class="card-deck mb-3 text-center">
            {% for product in my_info.products %}
            <div class="col-sm-3">
                <div class="card mb-4 shadow-sm">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-bold">{{product.name}}</h4>
                    </div>
                    <div class="card-body">
                        <img src="{{product.image}}" class="card-img-top">
                        <h1 class="card-title pricing-card-title precio">$<span class="">{{product.price}}</span></h1>

                        <ul class="list-unstyled mt-3 mb-4">
                            <li></li>
                            <li></li>
                            <li>{{product.description}}</li>
                            <li>id: {{product.id}}</li>
                        </ul>
                        <a href="" class="btn btn-block btn-primary agregar-carrito" data-id="{{product.id}}">Comprar</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <script>
        class Carrito {
            comprarProducto(e) {
                e.preventDefault();
                if (e.target.classList.contains('agregar-carrito')) {
                    const producto = e.target.parentElement.parentElement;
                    this.leerDatosProducto(producto);
                }
            }

            leerDatosProducto(producto) {
                const infoProducto = {
                    imagen: producto.querySelector('img').src,
                    titulo: producto.querySelector('h4').textContent,
                    precio: producto.querySelector('.precio span').textContent,
                    id: producto.querySelector('a').getAttribute('data-id'),
                    cantidad: 1
                }
                let productosLS;
                productosLS = this.obtenerProductosLocalStorage();
                productosLS.forEach(function(productoLS){
                    if (productoLS.id === infoProducto.id){
                        productosLS = productoLS.id;
                    }
                });
                if (productosLS === infoProducto.id){
                    Swal.fire({
                        type: 'info',
                        title: 'Oops...',
                        text: 'Producto ya agregado',
                        timer: 1000,
                        showConfirmButton: false
                    })
                }else{
                    this.insertarCarrito(infoProducto);
                }
                
            }

            insertarCarrito(producto) {
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td>
                        <img src="${producto.imagen}" width=100>
                    </td>
                    <td>${producto.titulo}</td>
                    <td>${producto.precio}</td>
                    <td>
                        <a href="#" class="borrar-producto fas fa-times-circle" data-id="${producto.id}"></a>
                    </td>`;
                listaProductos.appendChild(row);
                this.guardarProductosLocalStorage(producto)
            }

            eliminarProducto(e) {
                e.preventDefault();
                let producto, productoID;
                if (e.target.classList.contains('borrar-producto')) {
                    e.target.parentElement.parentElement.remove();
                    producto = e.target.parentElement.parentElement;
                    productoID = producto.querySelector('a').getAttribute('data-id');
                }
                this.eliminarProductoLocalStorage(productoID);
                this.calcularTotal();
            }

            vaciarCarrito(e) {
                e.preventDefault();
                while (listaProductos.firstChild) {
                    listaProductos.removeChild(listaProductos.firstChild);
                }
                this.vaciarLocalStorage();
                return false;
            }

            //Almacenar en el LS
            guardarProductosLocalStorage(producto) {
                let productos;
                //Toma valor de un arreglo con datos del LS
                productos = this.obtenerProductosLocalStorage();
                //Agregar el producto al carrito
                productos.push(producto);
                //Agregamos al LS
                localStorage.setItem('productos', JSON.stringify(productos));
            }

            //Comprobar que hay elementos en el LS
            obtenerProductosLocalStorage() {
                let productoLS;

                //Comprobar si hay algo en LS
                if (localStorage.getItem('productos') === null) {
                    productoLS = [];
                }
                else {
                    productoLS = JSON.parse(localStorage.getItem('productos'));
                }
                return productoLS;
            }

            //Mostrar los productos guardados en el LS
            leerLocalStorage() {
                let productosLS;
                productosLS = this.obtenerProductosLocalStorage();
                productosLS.forEach(function (producto) {
                    //Construir plantilla
                    const row = document.createElement('tr');
                    row.innerHTML = `
                <td>
                    <img src="${producto.imagen}" width=100>
                </td>
                <td>${producto.titulo}</td>
                <td>${producto.precio}</td>
                <td>
                    <a href="#" class="borrar-producto fas fa-times-circle" data-id="${producto.id}"></a>
                </td>`;
                    listaProductos.appendChild(row);
                });
            }

            //Eliminar producto por ID del LS
            eliminarProductoLocalStorage(productoID) {
                let productosLS;
                //Obtenemos el arreglo de productos
                productosLS = this.obtenerProductosLocalStorage();
                //Comparar el id del producto borrado con LS
                productosLS.forEach(function (productoLS, index) {
                    if (productoLS.id === productoID) {
                        productosLS.splice(index, 1);
                    }
                });

                //Añadimos el arreglo actual al LS
                localStorage.setItem('productos', JSON.stringify(productosLS));
            }

            //Eliminar todos los datos del LS
            vaciarLocalStorage() {
                localStorage.clear();
            }

            //Procesar pedido
            procesarPedido(e) {
                e.preventDefault();

                if (this.obtenerProductosLocalStorage().length === 0) {
                    Swal.fire({
                        type: 'info',
                        title: 'Oops...',
                        text: 'El carrito está vacio, agrega un producto',
                        timer: 2000,
                        showConfirmButton: false
                    })
                }
                else {
                    location.href = "{{ url_for('car.show_shopping_car') }}";
                }
            }
        }


        const carro = new Carrito();
        const carrito = document.getElementById('carrito');
        const productos = document.getElementById('lista-productos');
        const listaProductos = document.querySelector('#lista-carrito tbody');
        const vaciarCarritoBtn = document.getElementById('vaciar-carrito');
        const procesarPedidoBtn = document.getElementById('procesar-pedido');

        cargarEventos();

        function cargarEventos() {

            //Se ejecuta cuando se presionar agregar carrito
            productos.addEventListener('click', (e) => { carro.comprarProducto(e) });

            //Cuando se elimina productos del carrito
            carrito.addEventListener('click', (e) => { carro.eliminarProducto(e) });

            //Al vaciar carrito
            vaciarCarritoBtn.addEventListener('click', (e) => { carro.vaciarCarrito(e) });

            //Al cargar documento se muestra lo almacenado en LS
            document.addEventListener('DOMContentLoaded', carro.leerLocalStorage());

            //Enviar pedido a otra pagina
            procesarPedidoBtn.addEventListener('click', (e)=>{carro.procesarPedido(e)});
        }
    </script>

    <script type="text/javascript" scr="static/carrito.js"></script>
    <script type="text/javascript" scr="{{ url_for('static', filename='carrito.js') }}"></script>
    <script type="text/javascript" scr="{{ url_for('static', filename='pedido.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

Proyecto_flask/app/templates/category_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Categoria creada exitosamente!</title>
</head>
<body>
Categoria creada exitosamente!
</body>
</html>

Proyecto_flask/app/templates/myProfile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <title>My Profile</title>
</head>

<body>
    <div class="hero-head">
        <nav class="navbar" style="background-color: mediumslateblue;">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="{{ url_for('products.show_products_catalog') }}" class="navbar-item">
                            Catalog
                        </a>
                        <a href="{{ url_for('payment.add_payment_form') }}" class="navbar-item">
                            Add payment method
                        </a>
                        <a href="{{ url_for('auth.show_my_profile') }}" class="navbar-item">
                            My profile
                        </a>
                        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                            Logout
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 my-4 mx-auto text-center">
        <h1 class="display-4 mt-4">{{my_info.name}}</h1>
        <p class="lead">{{my_info.email}}</p>
    </div>
    <p></p>
    <p></p>
    <p class="lead" style="text-align: center;">MY PAYMENTS METHODS</p>
    <div class="card-deck mb-3 text-center">
        <div class="container">
            <div class="row">
                {% for payment in my_info.payments %}
                {% if payment.user_id == my_info.id %}
                <div class="col-sm-3">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-bold">{{payment.bank}}</h4>
                        </div>
                        <div class="card-body">
                            <p></p>
                            <h1 class="card-title pricing-card-title precio" style="font-size: 30px; font-weight: 300;">{{payment.id}}<span class=""></span></h1>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</body>

</html>

Proyecto_flask/app/templates/shopping.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <title>Shopping Car</title>

</head>

<body>
    <div class="hero-head">
        <nav class="navbar" style="background-color: mediumslateblue;">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="{{ url_for('products.show_products_catalog') }}" class="navbar-item">
                            Catalog
                        </a>
                        <a href="{{ url_for('payment.add_payment_form') }}" class="navbar-item">
                            Add payment method
                        </a>
                        <a href="{{ url_for('auth.show_my_profile') }}" class="navbar-item">
                            My profile
                        </a>
                        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                            Logout
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <br>

    <div class="container">
        <div class="row mt-3">
            <div class="col">
                <h2 class="d-flex justify-content-center mb-3">Realizar Compra</h2>
                <h2 class="d-flex justify-content-center mb-3">Cliente: {{my_info.name}}</h2>
                <h2 class="d-flex justify-content-center mb-3">Email: {{my_info.email}}</h2>
                <div id="carrito" class="form-group table-responsive">
                    <table class="table" id="lista-compra">
                        <thead>
                            <tr>
                                <th scope="col">Imagen</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Precio</th>
                                <th scope="col">Cantidad</th>
                                <th scope="col">Sub Total</th>
                                <th scope="col">Eliminar</th>
                            </tr>

                        </thead>
                        <tbody>

                        </tbody>
                        <tr>
                            <th colspan="4" scope="col" class="text-right">SUB TOTAL :</th>
                            <th scope="col">
                                <p id="subtotal"></p>
                            </th>
                        </tr>
                        <tr>
                            <th colspan="4" scope="col" class="text-right">IVA :</th>
                            <th scope="col">
                                <p id="iva"></p>
                            </th>
                        </tr>
                        <tr>
                            <th colspan="4" scope="col" class="text-right">TOTAL :</th>
                            <th scope="col">
                                <input id="total" name="monto" class="font-weight-bold border-0" readonly
                                    style="background-color: white;"></input>
                            </th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        class Carrito {

            eliminarProducto(e) {
                e.preventDefault();
                let producto, productoID;
                if (e.target.classList.contains('borrar-producto')) {
                    e.target.parentElement.parentElement.remove();
                    producto = e.target.parentElement.parentElement;
                    productoID = producto.querySelector('a').getAttribute('data-id');
                }
                this.eliminarProductoLocalStorage(productoID);
                this.calcularTotal();
            }

            //Comprobar que hay elementos en el LS
            obtenerProductosLocalStorage() {
                let productoLS;

                //Comprobar si hay algo en LS
                if (localStorage.getItem('productos') === null) {
                    productoLS = [];
                }
                else {
                    productoLS = JSON.parse(localStorage.getItem('productos'));
                }
                return productoLS;
            }

            //Mostrar los productos guardados en el LS en compra.html
            leerLocalStorageCompra() {
                let productosLS;
                productosLS = this.obtenerProductosLocalStorage();
                productosLS.forEach(function (producto) {
                    const row = document.createElement('tr');
                    row.innerHTML = `
                <td>
                    <img src="${producto.imagen}" width=100>
                </td>
                <td>${producto.titulo}</td>
                <td>${producto.precio}</td>
                <td>
                    <input type="number" class="form-control cantidad" min="1" value=${producto.cantidad}>
                </td>
                <td id='subtotales'>${producto.precio * producto.cantidad}</td>
                <td>
                    <a href="#" class="borrar-producto fas fa-times-circle" style="font-size:30px" data-id="${producto.id}"></a>
                </td>`;
                    listaCompra.appendChild(row);
                });
            }

            //Eliminar producto por ID del LS
            eliminarProductoLocalStorage(productoID) {
                let productosLS;
                //Obtenemos el arreglo de productos
                productosLS = this.obtenerProductosLocalStorage();
                //Comparar el id del producto borrado con LS
                productosLS.forEach(function (productoLS, index) {
                    if (productoLS.id === productoID) {
                        productosLS.splice(index, 1);
                    }
                });

                //Añadimos el arreglo actual al LS
                localStorage.setItem('productos', JSON.stringify(productosLS));
            }

            //Calcular montos
            calcularTotal() {
                let productosLS;
                let total = 0, iva = 0, subtotal = 0;
                productosLS = this.obtenerProductosLocalStorage();
                for (let i = 0; i < productosLS.length; i++) {
                    let element = Number(productosLS[i].precio * productosLS[i].cantidad);
                    total = total + element;
                }

                iva = parseFloat(total * 0.18).toFixed(2);
                subtotal = parseFloat(total - iva).toFixed(2);

                document.getElementById('subtotal').innerHTML = "S/. " + subtotal;
                document.getElementById('iva').innerHTML = "S/. " + iva;
                document.getElementById('total').value = "S/. " + total.toFixed(2);
            }

            obtenerEvento(e) {
                e.preventDefault();
                let id, cantidad, producto, productosLS;
                if (e.target.classList.contains('cantidad')) {
                    producto = e.target.parentElement.parentElement;
                    id = producto.querySelector('a').getAttribute('data-id');
                    cantidad = producto.querySelector('input').value;
                    let actualizarMontos = document.querySelectorAll('#subtotales');
                    productosLS = this.obtenerProductosLocalStorage();
                    productosLS.forEach(function (productoLS, index) {
                        if (productoLS.id === id) {
                            productoLS.cantidad = cantidad;
                            actualizarMontos[index].innerHTML = Number(cantidad * productosLS[index].precio);
                        }
                    });
                    localStorage.setItem('productos', JSON.stringify(productosLS));

                }
                else {
                    console.log("click afuera");
                }
            }
        }

        const compra = new Carrito();
        const listaCompra = document.querySelector("#lista-compra tbody");
        const carrito = document.getElementById('carrito');


        cargarEventos();

        function cargarEventos() {
            document.addEventListener('DOMContentLoaded', compra.leerLocalStorageCompra());

            //Eliminar productos del carrito
            carrito.addEventListener('click', (e) => { compra.eliminarProducto(e) });

            compra.calcularTotal();

            carrito.addEventListener('change', (e) => { compra.obtenerEvento(e) });
            carrito.addEventListener('keyup', (e) => { compra.obtenerEvento(e) });
        }

    </script>

    <script scr="{{ url_for('static', filename='carrito.js') }}"></script>
    <script scr="{{ url_for('static', filename='compra.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>